
// export 

// export default function DashboardLayout({
//     children,
// }: {
//     children: React.ReactNode
//   }) {
//     return <section>{children}</section>
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
// import "./font.css";
import NavBar from "./navbar/Navbar";
// import Footer from "./footer/Footer"
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <NavBar/>
        {children}
      {/* <Footer/> */}
        </body>
    </html>
  );
}
